#!/usr/bin/env bash

set -e

# Colours
COLOR_RED=$(tput setaf 1)
COLOR_GREEN=$(tput setaf 2)
COLOR_YELLOW=$(tput setaf 3)
COLOR_BLUE=$(tput setaf 4)
COLOR_RESET=$(tput sgr0)
SILENT=false
LARAVEL=false
PUBLIC_DIR=""
PHPVER=8.1

print() {
	if [[ "${SILENT}" = false ]]; then
		echo -e "$@"
	fi
}

usage() {
	printf "%s\n" \
		"setup-site [option]" \
		"" \
		"Create a web server configuration using the given project and php version"

	printf "\n%s\n" "Options"
	printf "\t%s\n\t\t%s\n\n" \
		"-s, --silent" "Do not print informational output" \
		"-l, --laravel" "Designate this as a laravel project - otherwise false" \
		"-p, --php-ver" "Override the default php version [default: ${PHPVER}]" \
		"-d, --dir" "Provide path to the project root directory" \
		"-h, --help" "Display this help message"
}

error() {
    print "${COLOR_RED}"
    print "${1}"
    print "${COLOR_RESET}"
}

info() {
    print "${COLOR_YELLOW}"
    print "${1}"
    print "${COLOR_RESET}"
}

if [[ "$EUID" -eq 0 ]]; then
    error "Do not run this script as root"
    usage
	exit 1
fi

# Parse arguments
while [ "$#" -gt 0 ]; do
	case "$1" in
	-p | --php-ver)
		PHPVER="$2"
		shift 2
		;;
	-d | --dir)
		PROJECT_DIR="$2"
		shift 2
		;;
	-s | --silent)
		SILENT=true
		shift 1
		;;
	-l | --laravel)
		LARAVEL=true
		shift 1
		;;
	-h | --help)
		usage
		exit
		;;
	-p=* | --php-ver=*)
		PHPVER="${1#*=}"
		shift 1
		;;
	-d=* | --dir=*)
		PROJECT_DIR="${1#*=}"
		shift 1
		;;
	*)
        error "Unknown option: $1"
		usage
		exit 1
		;;
	esac
done

if [[ -z $(command -v nginx) ]]; then
    info "Nginx not installed"
    read -rp "Install now? (y/N): " confirmation
    if [[ "${confirmation}" = [yY] || "${confirmation}" = [yY][eE][sS] ]]; then
        sudo apt update
        sudo apt install nginx
    else
        error "Please install nginx first!"
        usage
        exit 1
    fi
fi
sudo sed -i "s/www-data/${USER}/g" "/etc/nginx/nginx.conf"

if [[ -z $PROJECT_DIR ]]; then
	if [[ -z $(command -v fzf) ]]; then
        info "No project given and fzf (fuzzy finder) not installed"
        read -rp "Install now? (y/N): " confirmed
        if [[ "${confirmed}" = [yY] || "${confirmed}" = [yY][eE][sS] ]]; then
            sudo apt update
            sudo apt install fzf
        else
            error "Please either provide a project or install fzf"
            usage
            exit 1
        fi
	fi
	info "No project given, using fuzzy finder..."
	sleep 1
	PROJECT_DIR=$(find "${HOME}" -mindepth 1 -maxdepth 4 -type d | fzf)
fi

if [[ -z "$PROJECT_DIR" ]]; then
	error "Invalid project directory"
	usage
	exit 1
fi

# Get just the final project directory name without the path and without any leading or trailing whitespace or EOL/null characters
PROJECT_NAME=$(basename -z "${PROJECT_DIR}" | xargs --null)
if [[ -z "$PROJECT_NAME" ]]; then
	error "Invalid project name"
	usage
	exit 1
fi

# If a relative path is given, convert to a full path
BASE_PATH=$(dirname -z "${PROJECT_DIR}" | xargs --null)
BASE_PATH=$(cd "${BASE_PATH}"; pwd)
PROJECT_DIR="${BASE_PATH}/${PROJECT_NAME}"
PROJECT_NAME=$(echo "${PROJECT_NAME}" | tr " " "-")

PHP="php${PHPVER}"
if [[ -z $(which "${PHP}") ]]; then
	info "${PHP} not installed"
	read -rp "Install now? (y/N): " confirm
	if [[ "${confirm}" = [yY] || "${confirm}" = [yY][eE][sS] ]]; then
        if [[ -z $(find /etc/apt -type f -iname "ondrej-ubuntu-php*") ]]; then
            info "Adding ondrej/php ppa to the system repositories"
            sleep 1
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository ppa:ondrej/php
        fi
		sudo apt update
        sudo apt install "${PHP}" "${PHP}-fpm" "${PHP}-cli" "${PHP}-imagick" "${PHP}-intl" "${PHP}-redis" "${PHP}-yaml" "${PHP}-zip" "${PHP}-gnupg" -y
        sudo apt install "${PHP}-imap" "${PHP}-mysql" "${PHP}-gd" "${PHP}-mbstring" "${PHP}-curl" "${PHP}-xml" "${PHP}-bcmath" "${PHP}-xdebug" "${PHP}-pgsql" -y
        wget --quiet -O - https://raw.githubusercontent.com/benmoses-dev/linux-helper-scripts/main/xdebug3.ini | sudo tee "/etc/php/${PHPVER}/mods-available/xdebug.ini"
        print "PHP ${PHPVER} installed"
        sleep 1
	fi
fi

sudo systemctl enable --now "${PHP}-fpm.service"
sleep 1
sudo sed -i "s/www-data/${USER}/g" "/etc/php/${PHPVER}/fpm/pool.d/www.conf"
sudo systemctl restart "${PHP}-fpm.service"

if [[ "${LARAVEL}" == true ]]; then
	PUBLIC_DIR="/public"
fi

info "Setting up nginx server block..."
sleep 1
cat <<EOL | sudo tee "/etc/nginx/sites-available/${PROJECT_NAME}"
server {
	listen 80;
	listen [::]:80;

	server_name ${PROJECT_NAME}.local;
    root ${PROJECT_DIR}${PUBLIC_DIR};

	access_log /var/log/nginx/${PROJECT_NAME}-access.log;
    error_log  /var/log/nginx/${PROJECT_NAME}-error.log error;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
 
    index index.php;
 
    charset utf-8;
 
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }
 
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    error_page 404 /index.php;
 
    location ~ \.php\$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_pass unix:/run/php/php${PHPVER}-fpm.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
 
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
EOL

info "Creating symlinks..."
sleep 1
sudo rm -f "/etc/nginx/sites-enabled/${PROJECT_NAME}"
sudo ln -s "/etc/nginx/sites-available/${PROJECT_NAME}" "/etc/nginx/sites-enabled/${PROJECT_NAME}"

info "Restarting nginx..."
sleep 1

if sudo ss -tupln | grep -q "apache"; then
    sudo systemctl disable --now apache2
    sleep 5
fi

sudo nginx -t >/dev/null 2>&1
NGINX_SUCCESS=$?
if [[ $NGINX_SUCCESS -ne 0 ]]; then
	error "Something went wrong with the nginx configuration"
	error "Check the configuration file at /etc/nginx/sites-available/${PROJECT_NAME}"
    exit 1
fi

if ! sudo ss -tupln | grep -q "nginx"; then
    sudo systemctl enable --now nginx
    sleep 5
fi
sudo systemctl restart nginx

print "${COLOR_GREEN}"
print "Done! Go to ${PROJECT_NAME}.local to test the site"
print "${COLOR_RESET}"
sleep 1
